apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    env: prod
    owner: hassan
    webserver: nginx
    country: egypt
spec:
  containers:
    - name: nginx
      image: nginx:1.21.4
      ports:
        - containerPort: 80