apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  restartPolicy: Never
  volumes:
    - name: shared-area
      emptyDir: { }
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: shared-area
    - name: ubuntu-container
      image: ubuntu
      volumeMounts:
        - mountPath: /pod-area
          name: shared-area
      command: ["/bin/sh"]
      args: ["-c","echo Helloe from nerd mutli container > /pod-area/index.html"]
